service: jobs-gathering-service

plugins:
  - serverless-pseudo-parameters

custom:
  config: ${file(./config/${self:provider.stage}.json)}

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  stage: ${opt:stage}
  timeout: 10
  environment:
    NODE_ENV: '${opt:stage}'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:PutItem'
      Resource:
        - 'arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/jobs_*'

package:
  exclude:
    - ./**
    - '!node_modules/**'
    - 'node_modules/**/aws-sdk/**'
  include:
    - package.json
    - dist/**
    - config/**

functions:
  scrape-jobs:
    handler: dist/handlers.scrapeJobsHandler
  list-jobs:
    handler: dist/handlers.listJobsHandler
    events:
      - http:
          path: v1/jobs
          method: get
          cors: true
